
# This Makefile was generated by genmakefile.py, a Makefile generation script.
# For more information on genmakefile.py, refer to the genmakefile webpage at:
# http://www-personal.umich.edu/~gopalkri/MakefileGenerator/
# You may also contact the author of the script by email at: gopalkri@umich.edu
CC = gcc
LD = gcc

CFLAGS = -ansi -Wall -c -pedantic -D_GNU_SOURCE -std=c99 -g
LFLAGS = -lGLEW -lGL -lglut -lm -lGLU

OBJS = shader.o main.o

PROG = main

default: $(PROG)

$(PROG): $(OBJS)
	$(LD) $(LFLAGS) -o $(PROG) $(OBJS) 

shader.o: shader.c shader.h
	$(CC) $(CFLAGS) shader.c

main.o: main.c shader.h
	$(CC) $(CFLAGS) main.c

clean:
	rm -rf *.o

real_clean:
	 rm -rf *.o $(PROG)

